const TYPE =  {
    ADD_ARTICLE : 'abc',
    CLICK_DEMO : 'click',
    LISTEN_HIDE_DROPDOWN : 'HIDE_DROPDOWN',
    CHANGE_ACTIVE_MENU : "TOGGLE_ACTIVE_MENU",
    DETECT_CLIENT : "DETECT_CLIENT_JS",
    IDENTIFIER_CLICK_DROPDOWN : "IDENTIFIER_CLICK_DROPDOWN"
}
export default TYPE;