const TYPE =  {
    ADD_ARTICLE : 'abc',
    CLICK_DEMO : 'click',
    LISTEN_HIDE_DROPDOWN : 'HIDE_DROPDOWN',
    CHANGE_ACTIVE_MENU : "TOGGLE_ACTIVE_MENU",
    DETECT_CLIENT : "DETECT_CLIENT_JS",
    IDENTIFIER_CLICK_DROPDOWN : "IDENTIFIER_CLICK_DROPDOWN",
    IS_LOGGED : "IS_LOGGED",
    INITIAL_CONNECT_LST_PLAYER_ROOM : "INITIAL_CONNECT",
    INITIIAL : "INITIIAL",
    INITIIALSOCKET : "INITIIALSOCKET",
    RESET_USER_NULL : "RESET_USER_NULL"
}
export default TYPE;